export enum icon {
  add,
  addCircle,
  addSquare,
  addToCart,
  addUser,
  adjust,
  adn,
  alarm,
  alarmOutline,
  alarmSlash,
  alarmSlashOutline,
  alignCenter,
  alignJustify,
  alignLeft,
  alignRight,
  ambulance,
  americanExpress,
  amex,
  anchor,
  android,
  angellist,
  angleDoubleDown,
  angleDoubleLeft,
  angleDoubleRight,
  angleDoubleUp,
  angleDown,
  angleLeft,
  angleRight,
  angleUp,
  announcement,
  apple,
  archive,
  areaChart,
  areaGraph,
  arrowCircleDown,
  arrowCircleLeft,
  arrowCircleOutlineDown,
  arrowCircleOutlineLeft,
  arrowCircleOutlineRight,
  arrowCircleOutlineUp,
  arrowCircleRight,
  arrowCircleUp,
  arrowDown,
  arrowDownCart,
  arrowLeft,
  arrowRight,
  arrowUp,
  asexual,
  asterisk,
  at,
  attach,
  attention,
  backward,
  ban,
  bar,
  barChart,
  barcode,
  barGraph,
  bars,
  bed,
  beer,
  behance,
  behanceSquare,
  bell,
  bellOutline,
  bellSlash,
  bellSlashOutline,
  bicycle,
  binoculars,
  birthday,
  bitbucket,
  bitbucketSquare,
  bitcoin,
  blockLayout,
  bold,
  bomb,
  book,
  bookmark,
  bookmarkOutline,
  briefcase,
  browser,
  btc,
  bug,
  building,
  buildingOutline,
  bullhorn,
  bullseye,
  bus,
  buysellads,
  calculator,
  calendar,
  calendarOutline,
  call,
  callSquare,
  camera,
  cameraRetro,
  cancel,
  car,
  caretDown,
  caretLeft,
  caretRight,
  caretUp,
  cart,
  cc,
  certificate,
  chat,
  check,
  checkCircle,
  checkCircleOutline,
  checkmark,
  checkmarkBox,
  checkSquare,
  chevronCircleDown,
  chevronCircleLeft,
  chevronCircleRight,
  chevronCircleUp,
  chevronDown,
  chevronLeft,
  chevronRight,
  chevronUp,
  child,
  circle,
  circleNotched,
  circleOutline,
  circleThin,
  clipboard,
  clock,
  close,
  closedCaptioning,
  cloud,
  cloudDownload,
  cloudUpload,
  cocktail,
  code,
  codepen,
  coffee,
  cogs,
  columns,
  comment,
  commentOutline,
  comments,
  commentsOutline,
  compass,
  compose,
  compress,
  computer,
  configure,
  connectdevelop,
  content,
  conversation,
  copy,
  copyright,
  creditCard,
  crop,
  crosshairs,
  css3,
  cube,
  cubes,
  currency,
  cut,
  dashboard,
  dashcube,
  database,
  delete,
  delicious,
  desktop,
  detective,
  deviantart,
  diamond,
  digg,
  discover,
  discussions,
  diskOutline,
  dislikeOutline,
  doctor,
  dollar,
  dont,
  dotCircleOutline,
  download,
  dribbble,
  dropbox,
  dropdown,
  drupal,
  edit,
  eject,
  ellipsisHorizontal,
  ellipsisVertical,
  emergency,
  empire,
  emptyHeart,
  emptyStar,
  envelope,
  erase,
  eraser,
  eur,
  euro,
  exchange,
  expand,
  external,
  externalShare,
  externalSquare,
  eye,
  eyedropper,
  facebook,
  facebookSquare,
  fastBackward,
  fastForward,
  favorite,
  fax,
  feed,
  female,
  femaleHomosexual,
  fighterJet,
  file,
  fileArchiveOutline,
  fileAudioOutline,
  fileCodeOutline,
  fileExcelOutline,
  fileImageOutline,
  fileOutline,
  filePdfOutline,
  filePowerpointOutline,
  fileText,
  fileTextOutline,
  fileVideoOutline,
  fileWordOutline,
  film,
  filter,
  find,
  fire,
  fireExtinguisher,
  firstAid,
  flag,
  flagCheckered,
  flagOutline,
  flask,
  flickr,
  folder,
  folderOpen,
  folderOpenOutline,
  folderOutline,
  font,
  food,
  fork,
  forumbee,
  forward,
  foursquare,
  frown,
  game,
  gamepad,
  gay,
  gbp,
  genderless,
  gift,
  git,
  github,
  githubAlternate,
  githubSquare,
  gitSquare,
  gittip,
  globe,
  google,
  googlePlus,
  googlePlusSquare,
  googleWallet,
  graduation,
  gratipay,
  gridLayout,
  group,
  h,
  hackerNews,
  handicap,
  handOutlineDown,
  handOutlineLeft,
  handOutlineRight,
  handOutlineUp,
  hddOutline,
  header,
  headphone,
  heart,
  heartbeat,
  heartOutline,
  help,
  helpCircle,
  heterosexual,
  hide,
  history,
  home,
  hospital,
  hotel,
  html5,
  idea,
  ils,
  inbox,
  inCart,
  indent,
  info,
  infoCircle,
  inr,
  instagram,
  intergender,
  intersex,
  ioxhost,
  italic,
  joomla,
  jpy,
  jsfiddle,
  key,
  keyboard,
  krw,
  lab,
  laptop,
  lastfm,
  lastfmSquare,
  leaf,
  leanpub,
  legal,
  lemon,
  lesbian,
  levelDown,
  levelUp,
  lifeRing,
  lightbulb,
  lightning,
  like,
  likeOutline,
  lineChart,
  lineGraph,
  linkedin,
  linkedinSquare,
  linkify,
  linux,
  lira,
  list,
  listLayout,
  listOl,
  listUl,
  locationArrow,
  lock,
  logOut,
  longArrowDown,
  longArrowLeft,
  longArrowRight,
  longArrowUp,
  magic,
  magnet,
  magnify,
  mail,
  mailForward,
  mailOutline,
  mailSquare,
  male,
  maleHomosexual,
  man,
  map,
  marker,
  mars,
  marsAlternate,
  marsDouble,
  marsHorizontal,
  marsStroke,
  marsStrokeHorizontal,
  marsStrokeVertical,
  marsVertical,
  mastercard,
  maxcdn,
  maximize,
  meanpath,
  medium,
  medkit,
  meh,
  mercury,
  microphone,
  microphoneSlash,
  military,
  minimize,
  minus,
  minusCircle,
  minusSquare,
  minusSquareOutline,
  mobile,
  money,
  moon,
  motorcycle,
  move,
  music,
  mute,
  neuter,
  newspaper,
  nonBinaryTransgender,
  numberedList,
  openid,
  options,
  orderedList,
  otherGender,
  otherGenderHorizontal,
  otherGenderVertical,
  outdent,
  pagelines,
  paintBrush,
  paragraph,
  paste,
  pause,
  paw,
  payment,
  paypal,
  paypalCard,
  pencil,
  pencilSquare,
  phone,
  phoneSquare,
  photo,
  picture,
  pieChart,
  piedPiper,
  piedPiperAlternate,
  pieGraph,
  pin,
  pinterest,
  pinterestSquare,
  plane,
  play,
  playCircle,
  playCircleOutline,
  plug,
  plus,
  plusCart,
  plusCircle,
  plusSquare,
  plusSquareOutline,
  point,
  pointingDown,
  pointingLeft,
  pointingRight,
  pointingUp,
  pound,
  power,
  powerCord,
  print,
  privacy,
  protect,
  puzzle,
  qq,
  qrcode,
  question,
  quoteLeft,
  quoteRight,
  radio,
  rain,
  random,
  rebel,
  record,
  recycle,
  reddit,
  redditSquare,
  refresh,
  remove,
  removeBookmark,
  removeCircle,
  removeCircleOutline,
  removeUser,
  renren,
  repeat,
  reply,
  replyAll,
  resizeHorizontal,
  resizeVertical,
  retweet,
  road,
  rocket,
  rss,
  rssSquare,
  rub,
  ruble,
  rupee,
  save,
  search,
  selectedRadio,
  sellsy,
  send,
  sendOutline,
  server,
  setting,
  settings,
  share,
  shareAlternate,
  shareAlternateSquare,
  shareSquare,
  shekel,
  shield,
  ship,
  shipping,
  shirtsinbulk,
  shop,
  shoppingCart,
  shuffle,
  shutdown,
  sidebar,
  signal,
  signIn,
  signOut,
  signup,
  simplybuilt,
  sitemap,
  skyatlas,
  skype,
  slack,
  sliders,
  slideshare,
  smile,
  soccer,
  sort,
  sortAlphabetAscending,
  sortAlphabetDescending,
  sortAscending,
  sortContentAscending,
  sortContentDescending,
  sortDescending,
  sortNumericAscending,
  sortNumericDescending,
  sound,
  soundcloud,
  spaceShuttle,
  spinner,
  spoon,
  spotify,
  spy,
  square,
  squareOutline,
  stackExchange,
  stackOverflow,
  star,
  starHalf,
  starHalfEmpty,
  starHalfFull,
  steam,
  steamSquare,
  stepBackward,
  stepForward,
  stop,
  streetView,
  strikethrough,
  stripe,
  student,
  stumbleupon,
  stumbleuponCircle,
  subscript,
  subway,
  suitcase,
  sun,
  superscript,
  table,
  tablet,
  tag,
  tags,
  talk,
  target,
  tasks,
  taxi,
  teletype,
  tencentWeibo,
  terminal,
  textHeight,
  textTelephone,
  textWidth,
  theme,
  thumbsDown,
  thumbsOutlineDown,
  thumbsOutlineUp,
  thumbsUp,
  thumbTack,
  ticket,
  time,
  tint,
  toggleDown,
  toggleLeft,
  toggleOff,
  toggleOn,
  toggleRight,
  toggleUp,
  train,
  transgender,
  translate,
  trash,
  trashOutline,
  travel,
  treatment,
  tree,
  trello,
  triangleDown,
  triangleLeft,
  triangleRight,
  triangleUp,
  trophy,
  truck,
  try,
  tty,
  tumblr,
  tumblrSquare,
  twitch,
  twitter,
  twitterSquare,
  umbrella,
  underline,
  undo,
  unhide,
  university,
  unlink,
  unlock,
  unlockAlternate,
  unmute,
  unorderedList,
  upload,
  usd,
  user,
  userCancel,
  userClose,
  userDelete,
  users,
  userTimes,
  userX,
  venus,
  venusDouble,
  venusMars,
  viacoin,
  video,
  videoCamera,
  videoPlay,
  videoPlayOutline,
  vimeo,
  vine,
  visa,
  vk,
  volumeDown,
  volumeOff,
  volumeUp,
  wait,
  warning,
  warningCircle,
  warningSign,
  wechat,
  weibo,
  weixin,
  whatsapp,
  wifi,
  windows,
  winner,
  wizard,
  woman,
  won,
  wordpress,
  world,
  wrench,
  write,
  writeSquare,
  x,
  xing,
  xingSquare,
  yahoo,
  yelp,
  yen,
  youtube,
  youtubePlay,
  youtubeSquare,
  zip,
  zoom,
  zoomIn,
  zoomOut,
}

//generated by D:\LMCom\rew\CubesDeployment\SemanticFlag\SemanticFlagsEnum.cs
export enum flagShort {
  uae,

  ad,
  ae,
  af,
  ag,
  ai,
  al,
  am,
  an,
  ao,
  ar,
  as,
  at,
  au,
  aw,
  ax,
  az,
  ba,
  bb,
  bd,
  be,
  bf,
  bg,
  bh,
  bi,
  bj,
  bm,
  bn,
  bo,
  br,
  bs,
  bt,
  bv,
  bw,
  by,
  bz,
  ca,
  cc,
  cd,
  cf,
  cg,
  ch,
  ci,
  ck,
  cl,
  cm,
  cn,
  co,
  cr,
  cs,
  cu,
  cv,
  cx,
  cy,
  cz,
  de,
  dj,
  dk,
  dm,
  do,
  dz,
  ec,
  ee,
  eg,
  eh,
  er,
  es,
  et,
  eu,
  fi,
  fj,
  fk,
  fm,
  fo,
  fr,
  ga,
  gb,
  gbSct,
  gbWls,
  gd,
  ge,
  gf,
  gh,
  gi,
  gl,
  gm,
  gn,
  gp,
  gq,
  gr,
  gs,
  gt,
  gu,
  gw,
  gy,
  hk,
  hm,
  hn,
  hr,
  ht,
  hu,
  id,
  ie,
  il,
  in,
  io,
  iq,
  ir,
  is,
  it,
  jm,
  jo,
  jp,
  ke,
  kg,
  kh,
  ki,
  km,
  kn,
  kp,
  kr,
  kw,
  ky,
  kz,
  la,
  lb,
  lc,
  li,
  lk,
  lr,
  ls,
  lt,
  lu,
  lv,
  ly,
  ma,
  mc,
  md,
  me,
  mg,
  mh,
  mk,
  ml,
  mm,
  mn,
  mo,
  mp,
  mq,
  mr,
  ms,
  mt,
  mu,
  mv,
  mw,
  mx,
  my,
  mz,
  na,
  nc,
  ne,
  nf,
  ng,
  ni,
  nl,
  no,
  np,
  nr,
  nu,
  nz,
  om,
  pa,
  pe,
  pf,
  pg,
  ph,
  pk,
  pl,
  pm,
  pn,
  pr,
  ps,
  pt,
  pw,
  py,
  qa,
  re,
  ro,
  rs,
  ru,
  rw,
  sa,
  sb,
  sc,
  sd,
  se,
  sg,
  sh,
  si,
  sj,
  sk,
  sl,
  sm,
  sn,
  so,
  sr,
  st,
  sv,
  sy,
  sz,
  tc,
  td,
  tf,
  tg,
  th,
  tj,
  tk,
  tl,
  tm,
  tn,
  to,
  tr,
  tt,
  tv,
  tw,
  tz,
  ua,
  ug,
  um,
  us,
  uy,
  uz,
  va,
  vc,
  ve,
  vg,
  vi,
  vn,
  vu,
  wf,
  ws,
  ye,
  yt,
  za,
  zm,
  zw
}
export enum flag {
  burma,
  janMayen,
  unitedStates,

  afghanistan,
  alandIslands,
  albania,
  algeria,
  america,
  americanSamoa,
  andorra,
  angola,
  anguilla,
  antigua,
  argentina,
  armenia,
  aruba,
  australia,
  austria,
  azerbaijan,
  bahamas,
  bahrain,
  bangladesh,
  barbados,
  belarus,
  belgium,
  belize,
  benin,
  bermuda,
  bhutan,
  bolivia,
  bosnia,
  botswana,
  bouvetIsland,
  brazil,
  britishVirginIslands,
  brunei,
  bulgaria,
  burkinaFaso,
  burundi,
  caicosIslands,
  cambodia,
  cameroon,
  canada,
  capeVerde,
  caymanIslands,
  centralAfricanRepublic,
  chad,
  chile,
  china,
  christmasIsland,
  cocosIslands,
  colombia,
  comoros,
  congo,
  congoBrazzaville,
  cookIslands,
  costaRica,
  coteDivoire,
  croatia,
  cuba,
  cyprus,
  czechRepublic,
  denmark,
  djibouti,
  dominica,
  dominicanRepublic,
  ecuador,
  egypt,
  elSalvador,
  equatorialGuinea,
  eritrea,
  estonia,
  ethiopia,
  europeanUnion,
  falklandIslands,
  faroeIslands,
  fiji,
  finland,
  france,
  frenchGuiana,
  frenchPolynesia,
  frenchTerritories,
  gabon,
  gambia,
  georgia,
  germany,
  ghana,
  gibraltar,
  greece,
  greenland,
  grenada,
  guadeloupe,
  guam,
  guatemala,
  guinea,
  //guinea-bissau,
  guyana,
  haiti,
  heardIsland,
  honduras,
  hongKong,
  hungary,
  iceland,
  india,
  indianOceanTerritory,
  indonesia,
  iran,
  iraq,
  ireland,
  israel,
  italy,
  jamaica,
  japan,
  jordan,
  kazakhstan,
  kenya,
  kiribati,
  kuwait,
  kyrgyzstan,
  laos,
  latvia,
  lebanon,
  lesotho,
  liberia,
  libya,
  liechtenstein,
  lithuania,
  luxembourg,
  macau,
  macedonia,
  madagascar,
  malawi,
  malaysia,
  maldives,
  mali,
  malta,
  marshallIslands,
  martinique,
  mauritania,
  mauritius,
  mayotte,
  mexico,
  micronesia,
  moldova,
  monaco,
  mongolia,
  montenegro,
  montserrat,
  morocco,
  mozambique,
  myanmar,
  namibia,
  nauru,
  nepal,
  netherlands,
  netherlandsAntilles,
  newCaledonia,
  newGuinea,
  newZealand,
  nicaragua,
  niger,
  nigeria,
  niue,
  norfolkIsland,
  northernMarianaIslands,
  northKorea,
  norway,
  oman,
  pakistan,
  palau,
  palestine,
  panama,
  paraguay,
  peru,
  philippines,
  pitcairnIslands,
  poland,
  portugal,
  puertoRico,
  qatar,
  reunion,
  romania,
  russia,
  rwanda,
  saintHelena,
  saintKittsAndNevis,
  saintLucia,
  saintPierre,
  saintVincent,
  samoa,
  sandwichIslands,
  sanMarino,
  saoTome,
  saudiArabia,
  scotland,
  senegal,
  //serbia,
  serbia,
  seychelles,
  sierraLeone,
  singapore,
  slovakia,
  slovenia,
  solomonIslands,
  somalia,
  southAfrica,
  southKorea,
  spain,
  sriLanka,
  sudan,
  suriname,
  svalbard,
  swaziland,
  sweden,
  switzerland,
  syria,
  taiwan,
  tajikistan,
  tanzania,
  thailand,
  timorleste,
  togo,
  tokelau,
  tonga,
  trinidad,
  tunisia,
  turkey,
  turkmenistan,
  tuvalu,
  uganda,
  ukraine,
  unitedArabEmirates,
  unitedKingdom,
  uruguay,
  usMinorIslands,
  usVirginIslands,
  uzbekistan,
  vanuatu,
  vaticanCity,
  venezuela,
  vietnam,
  wales,
  wallisAndFutuna,
  westernSahara,
  yemen,
  zambia,
  zimbabwe,
}
export var flagMap =
  [
    { "short": "af", "long": "afghanistan" },
    { "short": "ax", "long": "alandIslands" },
    { "short": "al", "long": "albania" },
    { "short": "dz", "long": "algeria" },
    { "short": "us", "long": "america", "other": "unitedStates" },
    { "short": "as", "long": "americanSamoa" },
    { "short": "ad", "long": "andorra" },
    { "short": "ao", "long": "angola" },
    { "short": "ai", "long": "anguilla" },
    { "short": "ag", "long": "antigua" },
    { "short": "ar", "long": "argentina" },
    { "short": "am", "long": "armenia" },
    { "short": "aw", "long": "aruba" },
    { "short": "au", "long": "australia" },
    { "short": "at", "long": "austria" },
    { "short": "az", "long": "azerbaijan" },
    { "short": "bs", "long": "bahamas" },
    { "short": "bh", "long": "bahrain" },
    { "short": "bd", "long": "bangladesh" },
    { "short": "bb", "long": "barbados" },
    { "short": "by", "long": "belarus" },
    { "short": "be", "long": "belgium" },
    { "short": "bz", "long": "belize" },
    { "short": "bj", "long": "benin" },
    { "short": "bm", "long": "bermuda" },
    { "short": "bt", "long": "bhutan" },
    { "short": "bo", "long": "bolivia" },
    { "short": "ba", "long": "bosnia" },
    { "short": "bw", "long": "botswana" },
    { "short": "bv", "long": "bouvetIsland" },
    { "short": "br", "long": "brazil" },
    { "short": "vg", "long": "britishVirginIslands" },
    { "short": "bn", "long": "brunei" },
    { "short": "bg", "long": "bulgaria" },
    { "short": "bf", "long": "burkinaFaso" },
    { "short": "bi", "long": "burundi" },
    { "short": "tc", "long": "caicosIslands" },
    { "short": "kh", "long": "cambodia" },
    { "short": "cm", "long": "cameroon" },
    { "short": "ca", "long": "canada" },
    { "short": "cv", "long": "capeVerde" },
    { "short": "ky", "long": "caymanIslands" },
    { "short": "cf", "long": "centralAfricanRepublic" },
    { "short": "td", "long": "chad" },
    { "short": "cl", "long": "chile" },
    { "short": "cn", "long": "china" },
    { "short": "cx", "long": "christmasIsland" },
    { "short": "cc", "long": "cocosIslands" },
    { "short": "co", "long": "colombia" },
    { "short": "km", "long": "comoros" },
    { "short": "cd", "long": "congo" },
    { "short": "cg", "long": "congoBrazzaville" },
    { "short": "ck", "long": "cookIslands" },
    { "short": "cr", "long": "costaRica" },
    { "short": "ci", "long": "coteDivoire" },
    { "short": "hr", "long": "croatia" },
    { "short": "cu", "long": "cuba" },
    { "short": "cy", "long": "cyprus" },
    { "short": "cz", "long": "czechRepublic" },
    { "short": "dk", "long": "denmark" },
    { "short": "dj", "long": "djibouti" },
    { "short": "dm", "long": "dominica" },
    { "short": "do", "long": "dominicanRepublic" },
    { "short": "ec", "long": "ecuador" },
    { "short": "eg", "long": "egypt" },
    { "short": "sv", "long": "elSalvador" },
    { "short": "gq", "long": "equatorialGuinea" },
    { "short": "er", "long": "eritrea" },
    { "short": "ee", "long": "estonia" },
    { "short": "et", "long": "ethiopia" },
    { "short": "eu", "long": "europeanUnion" },
    { "short": "fk", "long": "falklandIslands" },
    { "short": "fo", "long": "faroeIslands" },
    { "short": "fj", "long": "fiji" },
    { "short": "fi", "long": "finland" },
    { "short": "fr", "long": "france" },
    { "short": "gf", "long": "frenchGuiana" },
    { "short": "pf", "long": "frenchPolynesia" },
    { "short": "tf", "long": "frenchTerritories" },
    { "short": "ga", "long": "gabon" },
    { "short": "gm", "long": "gambia" },
    { "short": "ge", "long": "georgia" },
    { "short": "de", "long": "germany" },
    { "short": "gh", "long": "ghana" },
    { "short": "gi", "long": "gibraltar" },
    { "short": "gr", "long": "greece" },
    { "short": "gl", "long": "greenland" },
    { "short": "gd", "long": "grenada" },
    { "short": "gp", "long": "guadeloupe" },
    { "short": "gu", "long": "guam" },
    { "short": "gt", "long": "guatemala" },
    { "short": "gn", "long": "guinea" },
    { "short": "gw", "long": "guinea-bissau" },
    { "short": "gy", "long": "guyana" },
    { "short": "ht", "long": "haiti" },
    { "short": "hm", "long": "heardIsland" },
    { "short": "hn", "long": "honduras" },
    { "short": "hk", "long": "hongKong" },
    { "short": "hu", "long": "hungary" },
    { "short": "is", "long": "iceland" },
    { "short": "in", "long": "india" },
    { "short": "io", "long": "indianOceanTerritory" },
    { "short": "id", "long": "indonesia" },
    { "short": "ir", "long": "iran" },
    { "short": "iq", "long": "iraq" },
    { "short": "ie", "long": "ireland" },
    { "short": "il", "long": "israel" },
    { "short": "it", "long": "italy" },
    { "short": "jm", "long": "jamaica" },
    { "short": "jp", "long": "japan" },
    { "short": "jo", "long": "jordan" },
    { "short": "kz", "long": "kazakhstan" },
    { "short": "ke", "long": "kenya" },
    { "short": "ki", "long": "kiribati" },
    { "short": "kw", "long": "kuwait" },
    { "short": "kg", "long": "kyrgyzstan" },
    { "short": "la", "long": "laos" },
    { "short": "lv", "long": "latvia" },
    { "short": "lb", "long": "lebanon" },
    { "short": "ls", "long": "lesotho" },
    { "short": "lr", "long": "liberia" },
    { "short": "ly", "long": "libya" },
    { "short": "li", "long": "liechtenstein" },
    { "short": "lt", "long": "lithuania" },
    { "short": "lu", "long": "luxembourg" },
    { "short": "mo", "long": "macau" },
    { "short": "mk", "long": "macedonia" },
    { "short": "mg", "long": "madagascar" },
    { "short": "mw", "long": "malawi" },
    { "short": "my", "long": "malaysia" },
    { "short": "mv", "long": "maldives" },
    { "short": "ml", "long": "mali" },
    { "short": "mt", "long": "malta" },
    { "short": "mh", "long": "marshallIslands" },
    { "short": "mq", "long": "martinique" },
    { "short": "mr", "long": "mauritania" },
    { "short": "mu", "long": "mauritius" },
    { "short": "yt", "long": "mayotte" },
    { "short": "mx", "long": "mexico" },
    { "short": "fm", "long": "micronesia" },
    { "short": "md", "long": "moldova" },
    { "short": "mc", "long": "monaco" },
    { "short": "mn", "long": "mongolia" },
    { "short": "me", "long": "montenegro" },
    { "short": "ms", "long": "montserrat" },
    { "short": "ma", "long": "morocco" },
    { "short": "mz", "long": "mozambique" },
    { "short": "mm", "long": "myanmar", "other": "burma" },
    { "short": "na", "long": "namibia" },
    { "short": "nr", "long": "nauru" },
    { "short": "np", "long": "nepal" },
    { "short": "nl", "long": "netherlands" },
    { "short": "an", "long": "netherlandsAntilles" },
    { "short": "nc", "long": "newCaledonia" },
    { "short": "pg", "long": "newGuinea" },
    { "short": "nz", "long": "newZealand" },
    { "short": "ni", "long": "nicaragua" },
    { "short": "ne", "long": "niger" },
    { "short": "ng", "long": "nigeria" },
    { "short": "nu", "long": "niue" },
    { "short": "nf", "long": "norfolkIsland" },
    { "short": "mp", "long": "northernMarianaIslands" },
    { "short": "kp", "long": "northKorea" },
    { "short": "no", "long": "norway" },
    { "short": "om", "long": "oman" },
    { "short": "pk", "long": "pakistan" },
    { "short": "pw", "long": "palau" },
    { "short": "ps", "long": "palestine" },
    { "short": "pa", "long": "panama" },
    { "short": "py", "long": "paraguay" },
    { "short": "pe", "long": "peru" },
    { "short": "ph", "long": "philippines" },
    { "short": "pn", "long": "pitcairnIslands" },
    { "short": "pl", "long": "poland" },
    { "short": "pt", "long": "portugal" },
    { "short": "pr", "long": "puertoRico" },
    { "short": "qa", "long": "qatar" },
    { "short": "re", "long": "reunion" },
    { "short": "ro", "long": "romania" },
    { "short": "ru", "long": "russia" },
    { "short": "rw", "long": "rwanda" },
    { "short": "sh", "long": "saintHelena" },
    { "short": "kn", "long": "saintKittsAndNevis" },
    { "short": "lc", "long": "saintLucia" },
    { "short": "pm", "long": "saintPierre" },
    { "short": "vc", "long": "saintVincent" },
    { "short": "ws", "long": "samoa" },
    { "short": "gs", "long": "sandwichIslands" },
    { "short": "sm", "long": "sanMarino" },
    { "short": "st", "long": "saoTome" },
    { "short": "sa", "long": "saudiArabia" },
    { "short": "gbSct", "long": "scotland" },
    { "short": "sn", "long": "senegal" },
    { "short": "cs", "long": "serbia" },
    { "short": "rs", "long": "serbia" },
    { "short": "sc", "long": "seychelles" },
    { "short": "sl", "long": "sierraLeone" },
    { "short": "sg", "long": "singapore" },
    { "short": "sk", "long": "slovakia" },
    { "short": "si", "long": "slovenia" },
    { "short": "sb", "long": "solomonIslands" },
    { "short": "so", "long": "somalia" },
    { "short": "za", "long": "southAfrica" },
    { "short": "kr", "long": "southKorea" },
    { "short": "es", "long": "spain" },
    { "short": "lk", "long": "sriLanka" },
    { "short": "sd", "long": "sudan" },
    { "short": "sr", "long": "suriname" },
    { "short": "sj", "long": "svalbard", "other": "janMayen" },
    { "short": "sz", "long": "swaziland" },
    { "short": "se", "long": "sweden" },
    { "short": "ch", "long": "switzerland" },
    { "short": "sy", "long": "syria" },
    { "short": "tw", "long": "taiwan" },
    { "short": "tj", "long": "tajikistan" },
    { "short": "tz", "long": "tanzania" },
    { "short": "th", "long": "thailand" },
    { "short": "tl", "long": "timorleste" },
    { "short": "tg", "long": "togo" },
    { "short": "tk", "long": "tokelau" },
    { "short": "to", "long": "tonga" },
    { "short": "tt", "long": "trinidad" },
    { "short": "tn", "long": "tunisia" },
    { "short": "tr", "long": "turkey" },
    { "short": "tm", "long": "turkmenistan" },
    { "short": "tv", "long": "tuvalu" },
    { "short": "ug", "long": "uganda" },
    { "short": "ua", "long": "ukraine" },
    { "short": "ae", "long": "unitedArabEmirates", "other": "uae" },
    { "short": "gb", "long": "unitedKingdom" },
    { "short": "uy", "long": "uruguay" },
    { "short": "um", "long": "usMinorIslands" },
    { "short": "vi", "long": "usVirginIslands" },
    { "short": "uz", "long": "uzbekistan" },
    { "short": "vu", "long": "vanuatu" },
    { "short": "va", "long": "vaticanCity" },
    { "short": "ve", "long": "venezuela" },
    { "short": "vn", "long": "vietnam" },
    { "short": "gbWls", "long": "wales" },
    { "short": "wf", "long": "wallisAndFutuna" },
    { "short": "eh", "long": "westernSahara" },
    { "short": "ye", "long": "yemen" },
    { "short": "zm", "long": "zambia" },
    { "short": "zw", "long": "zimbabwe" }
  ];
